# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39ff69afee839d2b4825a2aa2df79a95237ea7514bdaabbbce5836b2d77549bf1cdc68c6afd86b91746d516421c08a4006fa5d81911c598e2a23ebbd95581fa7

test:
  secret_key_base: 63f7d6857e39cdc777d82087caf1d2b2b32cfcc0395d464eb063b1100fc4b67d16ce6a3e4123c02ed5f31ec8a3d7a21953bbdf3bb746aa437c29b174411e6b49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
